[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | _build
  | weights
  | buck-out
  | yolo5
  | build
  | dist
  | venv
)/
'''

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"